language: python
dist: xenial
sudo: true

python:
  - 3.9

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORA_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_succes:
  - pipnev run codecov