name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv sync -d
    - name: Lint with flake8
      run: |
        pipenv install flake8
        flake8 .
    - name: Testing and coverage
        run: |
          pipenv install flake8
          flake8 .
          pipenv run pytest --cov=pypro